{"uid":"100563e90db27b25","name":"Sing in with LinkedIn","fullName":"cypress\\e2e\\specs\\SingInUsingLinkedIn.cy.js#SingInUsingLinkedIn.cy.js Sing in with LinkedIn","historyId":"d059273ec2f19a05c92686f4265a205c:d41d8cd98f00b204e9800998ecf8427e","time":{"start":1713356661249,"stop":1713356674071,"duration":12822},"status":"broken","statusMessage":"Timed out retrying after 4000ms: The command was expected to run against origin `https://www.linkedin.com` but the application is at origin `https://www.staging.youtrainers.com`.\n\nThis commonly happens when you have either not navigated to the expected origin or have navigated away unexpectedly.\n\nUsing `cy.origin()` to wrap the commands run on `https://www.staging.youtrainers.com` will likely fix this issue.\n\n`cy.origin('https://www.staging.youtrainers.com', () => {`\n`  <commands targeting https://www.staging.youtrainers.com go here>`\n`})`\n\nhttps://on.cypress.io/cy-visit-succeeded-but-commands-fail","statusTrace":"CypressError: Timed out retrying after 4000ms: The command was expected to run against origin `https://www.linkedin.com` but the application is at origin `https://www.staging.youtrainers.com`.\n\nThis commonly happens when you have either not navigated to the expected origin or have navigated away unexpectedly.\n\nUsing `cy.origin()` to wrap the commands run on `https://www.staging.youtrainers.com` will likely fix this issue.\n\n`cy.origin('https://www.staging.youtrainers.com', () => {`\n`  <commands targeting https://www.staging.youtrainers.com go here>`\n`})`\n\nhttps://on.cypress.io/cy-visit-succeeded-but-commands-fail\n    at Context.eval (webpack://Youtrainers/./cypress/e2e/specs/SingInUsingLinkedIn.cy.js:7:9)\nFrom Your Spec Code:\n    at Context.eval (webpack://Youtrainers/./cypress/e2e/specs/SingInUsingLinkedIn.cy.js:7:9)","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"broken","statusMessage":"Timed out retrying after 4000ms: The command was expected to run against origin `https://www.linkedin.com` but the application is at origin `https://www.staging.youtrainers.com`.\n\nThis commonly happens when you have either not navigated to the expected origin or have navigated away unexpectedly.\n\nUsing `cy.origin()` to wrap the commands run on `https://www.staging.youtrainers.com` will likely fix this issue.\n\n`cy.origin('https://www.staging.youtrainers.com', () => {`\n`  <commands targeting https://www.staging.youtrainers.com go here>`\n`})`\n\nhttps://on.cypress.io/cy-visit-succeeded-but-commands-fail","statusTrace":"CypressError: Timed out retrying after 4000ms: The command was expected to run against origin `https://www.linkedin.com` but the application is at origin `https://www.staging.youtrainers.com`.\n\nThis commonly happens when you have either not navigated to the expected origin or have navigated away unexpectedly.\n\nUsing `cy.origin()` to wrap the commands run on `https://www.staging.youtrainers.com` will likely fix this issue.\n\n`cy.origin('https://www.staging.youtrainers.com', () => {`\n`  <commands targeting https://www.staging.youtrainers.com go here>`\n`})`\n\nhttps://on.cypress.io/cy-visit-succeeded-but-commands-fail\n    at Context.eval (webpack://Youtrainers/./cypress/e2e/specs/SingInUsingLinkedIn.cy.js:7:9)\nFrom Your Spec Code:\n    at Context.eval (webpack://Youtrainers/./cypress/e2e/specs/SingInUsingLinkedIn.cy.js:7:9)","steps":[],"attachments":[{"uid":"18d888aca99f0455","name":"Screenshot","source":"18d888aca99f0455.png","type":"image/png","size":213413},{"uid":"d4ae90725d5ada4b","name":"Video","source":"d4ae90725d5ada4b.mp4","type":"video/mp4","size":2576783}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":2,"hasContent":true},"afterStages":[],"labels":[{"name":"language","value":"javascript"},{"name":"framework","value":"cypress"},{"name":"parentSuite","value":"SingInUsingLinkedIn.cy.js"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"ed452f08efcc2705","reportUrl":"https://isfortest.github.io/Youtrainers/4//#testresult/ed452f08efcc2705","status":"broken","statusDetails":"Timed out retrying after 4000ms: The command was expected to run against origin `https://www.linkedin.com` but the application is at origin `https://www.staging.youtrainers.com`.\n\nThis commonly happens when you have either not navigated to the expected origin or have navigated away unexpectedly.\n\nUsing `cy.origin()` to wrap the commands run on `https://www.staging.youtrainers.com` will likely fix this issue.\n\n`cy.origin('https://www.staging.youtrainers.com', () => {`\n`  <commands targeting https://www.staging.youtrainers.com go here>`\n`})`\n\nhttps://on.cypress.io/cy-visit-succeeded-but-commands-fail","time":{"start":1713356661249,"stop":1713356674071,"duration":12822}},{"uid":"fea7b84a3306dde5","reportUrl":"https://isfortest.github.io/Youtrainers/3//#testresult/fea7b84a3306dde5","status":"broken","statusDetails":"Timed out retrying after 4000ms: The command was expected to run against origin `https://www.linkedin.com` but the application is at origin `https://www.staging.youtrainers.com`.\n\nThis commonly happens when you have either not navigated to the expected origin or have navigated away unexpectedly.\n\nUsing `cy.origin()` to wrap the commands run on `https://www.staging.youtrainers.com` will likely fix this issue.\n\n`cy.origin('https://www.staging.youtrainers.com', () => {`\n`  <commands targeting https://www.staging.youtrainers.com go here>`\n`})`\n\nhttps://on.cypress.io/cy-visit-succeeded-but-commands-fail","time":{"start":1713356661249,"stop":1713356674071,"duration":12822}}]},"tags":[]},"source":"100563e90db27b25.json","parameterValues":[]}