{"uid":"112515ae7f4827c9","name":"Sing in with LinkedIn","fullName":"cypress\\e2e\\specs\\SingInUsingLinkedIn.cy.js#SingInUsingLinkedIn.cy.js Sing in with LinkedIn","historyId":"d059273ec2f19a05c92686f4265a205c:d41d8cd98f00b204e9800998ecf8427e","time":{"start":1713014167528,"stop":1713014182905,"duration":15377},"status":"broken","statusMessage":"Timed out retrying after 4000ms: The command was expected to run against origin `https://www.linkedin.com` but the application is at origin `https://www.staging.youtrainers.com`.\n\nThis commonly happens when you have either not navigated to the expected origin or have navigated away unexpectedly.\n\nUsing `cy.origin()` to wrap the commands run on `https://www.staging.youtrainers.com` will likely fix this issue.\n\n`cy.origin('https://www.staging.youtrainers.com', () => {`\n`  <commands targeting https://www.staging.youtrainers.com go here>`\n`})`\n\nhttps://on.cypress.io/cy-visit-succeeded-but-commands-fail","statusTrace":"CypressError: Timed out retrying after 4000ms: The command was expected to run against origin `https://www.linkedin.com` but the application is at origin `https://www.staging.youtrainers.com`.\n\nThis commonly happens when you have either not navigated to the expected origin or have navigated away unexpectedly.\n\nUsing `cy.origin()` to wrap the commands run on `https://www.staging.youtrainers.com` will likely fix this issue.\n\n`cy.origin('https://www.staging.youtrainers.com', () => {`\n`  <commands targeting https://www.staging.youtrainers.com go here>`\n`})`\n\nhttps://on.cypress.io/cy-visit-succeeded-but-commands-fail\n    at Context.eval (webpack://Youtrainers/./cypress/e2e/specs/SingInUsingLinkedIn.cy.js:7:9)\nFrom Your Spec Code:\n    at Context.eval (webpack://Youtrainers/./cypress/e2e/specs/SingInUsingLinkedIn.cy.js:7:9)","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"broken","statusMessage":"Timed out retrying after 4000ms: The command was expected to run against origin `https://www.linkedin.com` but the application is at origin `https://www.staging.youtrainers.com`.\n\nThis commonly happens when you have either not navigated to the expected origin or have navigated away unexpectedly.\n\nUsing `cy.origin()` to wrap the commands run on `https://www.staging.youtrainers.com` will likely fix this issue.\n\n`cy.origin('https://www.staging.youtrainers.com', () => {`\n`  <commands targeting https://www.staging.youtrainers.com go here>`\n`})`\n\nhttps://on.cypress.io/cy-visit-succeeded-but-commands-fail","statusTrace":"CypressError: Timed out retrying after 4000ms: The command was expected to run against origin `https://www.linkedin.com` but the application is at origin `https://www.staging.youtrainers.com`.\n\nThis commonly happens when you have either not navigated to the expected origin or have navigated away unexpectedly.\n\nUsing `cy.origin()` to wrap the commands run on `https://www.staging.youtrainers.com` will likely fix this issue.\n\n`cy.origin('https://www.staging.youtrainers.com', () => {`\n`  <commands targeting https://www.staging.youtrainers.com go here>`\n`})`\n\nhttps://on.cypress.io/cy-visit-succeeded-but-commands-fail\n    at Context.eval (webpack://Youtrainers/./cypress/e2e/specs/SingInUsingLinkedIn.cy.js:7:9)\nFrom Your Spec Code:\n    at Context.eval (webpack://Youtrainers/./cypress/e2e/specs/SingInUsingLinkedIn.cy.js:7:9)","steps":[],"attachments":[{"uid":"e2bb6bab4bfbffb7","name":"Screenshot","source":"e2bb6bab4bfbffb7.png","type":"image/png","size":242259}],"parameters":[],"shouldDisplayMessage":true,"attachmentsCount":1,"hasContent":true,"attachmentStep":false,"stepsCount":0},"afterStages":[],"labels":[{"name":"language","value":"javascript"},{"name":"framework","value":"cypress"},{"name":"parentSuite","value":"SingInUsingLinkedIn.cy.js"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":true,"retry":true,"extra":{"categories":[],"tags":[]},"source":"112515ae7f4827c9.json","parameterValues":[]}